config/routes.rb
Rails.application.routes.draw do
  scope 'users' do
    get 'sign_in', to: 'users/sessions#new'
    post 'sign_in', to: 'users/sessions#create', as: :user_session
    delete 'sign_out', to: 'users/sessions#destroy'

    get 'sign_up', to: 'users/registrations#new'
    post 'sign_up', to: 'users/registrations#create', as: :user_registration
  end

  namespace :screens do
    get :guest, action: 'guest'
    get :normal, action: 'normal'
    get :team, action: 'team'
  end

  namespace :tests do
    get 'ping'
    post 'voice'
  end

  get :settings, to: 'settings#show'

  resources :raspberries, only: [:index, :create, :update, :destroy]
  resources :reminders, only: [:index, :create, :destroy] do
    delete :erase_all, on: :collection
  end
  resources :settings, only: :update
  resources :voice_recognition_servers, only: :update
  resources :users, only: [:index, :create, :update, :destroy] do
    get :myself, on: :collection
  end

  root 'screens#team'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
    def authenticate
      authenticate_by_session || render_unauthorized
    end

    def authorize
      @current_user['attributes']['approved'] == true || render_forbidden
    end

    def authorize_admin
      (@current_user['attributes']['approved'] == true && @current_user['attributes']['admin'] == true) || render_forbidden
    end

  private
    def authenticate_by_session
      @current_user = (session[:current_user].present?) ? session[:current_user].with_indifferent_access : nil
    end

    def render_unauthorized
      redirect_to sign_in_path, notice: 'Non autorisé' and return
    end

    def render_forbidden
      respond_to do |format|
        format.html { redirect_to sign_in_path, notice: 'Droits administrateur requis' and return }
        format.json { render json: { droits: 'Interdit' }, status: :forbidden and return }
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_errors errors
    if errors.is_a? Hash
      pretty_msg = '<ul>'

      errors.each do |attr, errors_msg|
        msg = if errors_msg.is_a? Array
          errors_msg.to_sentence
        else
          errors_msg.first
        end

        pretty_msg << "<li>#{attr} : #{msg}</li>"
      end

      pretty_msg << '</ul>'
    else
      errors
    end
  end
end

app/views/application/_sidebar.html.slim
nav
  .nav-wrapper
    a.sidebar href='#' data-activates='sidebar-nav'
      i.material-icons menu

    #sidebar-nav.side-nav.fixed
      current-user-show :current-user='currentUser' api-url='#{ENV["api_url_http"]}' api-port='#{ENV["api_port_http"]}'

      ul
        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('users-index')"
              .row
                .col.s3
                  i.material-icons people

                .col.s7
                  | Utilisateurs

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('users-index')"
              .row
                .col.s3
                  i.material-icons people

                .col.s7
                  | Utilisateurs

        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('raspberries-index')"
              .row
                .col.s3
                  i.material-icons personal_video

                .col.s7
                  | Raspberry

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('raspberries-index')"
              .row
                .col.s3
                  i.material-icons personal_video

                .col.s7
                  | Raspberry

        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('voice-recognition-server-show')"
              .row
                .col.s3
                  i.material-icons settings_voice

                .col.s7
                  | SARAH

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('voice-recognition-server-show')"
              .row
                .col.s3
                  i.material-icons settings_voice

                .col.s7
                  | SARAH

        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('reminders-index')"
              .row
                .col.s3
                  i.material-icons notifications

                .col.s7
                  | Mémos

                  span.new.badge v-if="!hideBadgeNewReminders"
                    | {{ numberReceivedReminders }}

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('reminders-index')"
              .row
                .col.s3
                  i.material-icons notifications

                .col.s7
                  | Mémos

        / li
        /   .hide-on-med-and-down
        /     a href='#' @click.stop="changeCurrentView('voice-commands-index')"
        /       .row
        /         .col.s3
        /           i.material-icons record_voice_over

        /         .col.s7
        /           | Commandes vocales

        /   .hide-on-large-only
        /     a href='#' @click.prevent="changeCurrentView('voice-commands-index')"
        /       .row
        /         .col.s3
        /           i.material-icons record_voice_over

        /         .col.s7
        /           | Commandes vocales

        li.separator

        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('setting-show')"
              .row
                .col.s3
                  i.material-icons settings

                .col.s7
                  | Paramètres

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('setting-show')"
                .row
                  .col.s3
                    i.material-icons settings

                  .col.s7
                    | Paramètres

        li
          .hide-on-med-and-down
            a href='#' @click.stop="changeCurrentView('about-show')"
              .row
                .col.s3
                  i.material-icons info

                .col.s7
                  | Crédits

          .hide-on-large-only
            a href='#' @click.prevent="changeCurrentView('about-show')"
              .row
                .col.s3
                  i.material-icons info

                .col.s7
                  | Crédits

      = form_tag sign_out_path, method: :delete
        = submit_tag 'Déconnexion', class: 'btn-flat'